// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKrkbTp4dCnC39tz8EQiiTfoW-Khnwrq8',
    appId: '1:438372412254:web:6b6fb22095367826923dcf',
    messagingSenderId: '438372412254',
    projectId: 'scorebuddy-5e069',
    authDomain: 'scorebuddy-5e069.firebaseapp.com',
    storageBucket: 'scorebuddy-5e069.firebasestorage.app',
    measurementId: 'G-J8GJVYBH9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0jbSfmYwgBzqgk_Fv6VAP0EQfbc4bC3c',
    appId: '1:438372412254:android:3a48a82aa43ca4d2923dcf',
    messagingSenderId: '438372412254',
    projectId: 'scorebuddy-5e069',
    storageBucket: 'scorebuddy-5e069.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQrc8X3tCfgtdTHXBrJTwBDZ_Btu-ReiQ',
    appId: '1:438372412254:ios:93b089d66fa6bc10923dcf',
    messagingSenderId: '438372412254',
    projectId: 'scorebuddy-5e069',
    storageBucket: 'scorebuddy-5e069.firebasestorage.app',
    iosBundleId: 'com.example.autoEntrepreneurManager',
  );

}